#------------------------------------
# GMmanager Config File Version: 1.0
#------------------------------------

#ゲームモードを変更した際に表示されるメッセージ
#カラーコードが使えます
GameMode:
  Help:
    - ''
    - '&b&lヘルプメニュー'
    - '&7-----------------------------'
    - '&a/gm help: &3ヘルプの表示'
    - '&a/gm reload: &3リロードコマンド'
    - '&a/gm 0: &3サバイバルモード'
    - '&a/gm 1: &3クリエイティブモード'
    - '&a/gm 2: &3アドベンチャーモード'
    - '&a/gm 3: &3スペクテイターモード'

#権限エラー
  Error:
    - '&cあなたには権限がありません'

#リロード
  Reload:
    - 'Configを再読み込みしました'

#サバイバルモード
  Survival:
    - 'サバイバルモードに変更しました'

#クリエイティブモード
  Creative:
    - 'クリエイティブモードに変更しました'

#アドベンチャーモード
  Adventure:
    - 'アドベンチャーモードに変更しました'

#スペクテイターモード
  Spectator:
    - 'スペクテイターモードに変更しました'
