#------------------------------------
# GMmanager Config File Version: 1.0
#------------------------------------

#ゲームモードを変更した際に表示されるメッセージ
#カラーコードが使えます
GameMode:
#ヘルプ
  Help:
    - ''
    - '&b&lヘルプメニュー'
    - '&7-----------------------------'
    - '&3ヘルプの表示: &a/gm help'
    - '&3リロードコマンド: &a/gm reload'
    - '&3サバイバルモード: &a/gm 0'
    - '&3クリエイティブモード: &a/gm 1'
    - '&3アドベンチャーモード: &a/gm 2'
    - '&3スペクテイターモード: &a/gm 3'

#権限エラー
  Error:
    - '&cあなたには権限がありません'

#リロード
  Reload:
    - 'Configを再読み込みしました'

#サバイバルモード
  Survival:
    - 'サバイバルモードに変更しました'

#クリエイティブモード
  Creative:
    - 'クリエイティブモードに変更しました'

#アドベンチャーモード
  Adventure:
    - 'アドベンチャーモードに変更しました'

#スペクテイターモード
  Spectator:
    - 'スペクテイターモードに変更しました'